CREATE TABLE knowledge_base (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(100) NOT NULL CHECK (btrim(name) <> ''),
                                description VARCHAR(2000) NOT NULL DEFAULT '',
                                owner_id VARCHAR(100) NOT NULL CHECK (btrim(owner_id) <> ''),
                                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE knowledge_base IS '知识库';
COMMENT ON COLUMN knowledge_base.id IS '知识库主键，自增编号';
COMMENT ON COLUMN knowledge_base.name IS '知识库名称';
COMMENT ON COLUMN knowledge_base.description IS '知识库描述';
COMMENT ON COLUMN knowledge_base.owner_id IS '知识库所有者标识';
COMMENT ON COLUMN knowledge_base.created_at IS '知识库创建时间';
COMMENT ON COLUMN knowledge_base.updated_at IS '知识库更新时间';

-- 默认库用于承接历史资料和原有上传、查询接口。
INSERT INTO knowledge_base (id, name, description, owner_id)
VALUES (1, '默认知识库', '历史资料及原有接口使用的知识库', 'admin');

SELECT setval(pg_get_serial_sequence('knowledge_base', 'id'), 1, true);

CREATE TABLE ai_app (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL CHECK (btrim(name) <> ''),
                        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_knowledge_base (
                                    app_id BIGINT NOT NULL REFERENCES ai_app(id) ON DELETE CASCADE,
                                    knowledge_base_id BIGINT NOT NULL REFERENCES knowledge_base(id),
                                    PRIMARY KEY (app_id, knowledge_base_id)
);

COMMENT ON TABLE ai_app IS '人工智能应用';
COMMENT ON COLUMN ai_app.id IS '应用主键，自增编号';
COMMENT ON COLUMN ai_app.name IS '应用名称';
COMMENT ON COLUMN ai_app.created_at IS '应用创建时间';

COMMENT ON TABLE app_knowledge_base IS '应用与知识库关联关系';
COMMENT ON COLUMN app_knowledge_base.app_id IS '应用编号，关联人工智能应用';
COMMENT ON COLUMN app_knowledge_base.knowledge_base_id IS '知识库编号，关联知识库';

CREATE INDEX idx_app_knowledge_base_kb
    ON app_knowledge_base (knowledge_base_id);

-- V1 已创建 knowledge_import。
-- 兼容此前写入 knowledge_pdf_import 的记录。
DO $$
BEGIN
    IF to_regclass('public.knowledge_pdf_import') IS NOT NULL THEN
        INSERT INTO knowledge_import (file_hash, filename, created_at)
SELECT file_hash, filename, created_at
FROM knowledge_pdf_import
    ON CONFLICT (file_hash) DO NOTHING;
END IF;
END $$;

ALTER TABLE knowledge_import
    ADD COLUMN knowledge_base_id BIGINT NOT NULL DEFAULT 1
        REFERENCES knowledge_base(id);

COMMENT ON COLUMN knowledge_import.knowledge_base_id IS '导入文件所属知识库编号，关联知识库';

ALTER TABLE knowledge_import
DROP CONSTRAINT knowledge_import_pkey;

ALTER TABLE knowledge_import
    ADD PRIMARY KEY (knowledge_base_id, file_hash);

-- 新写入必须明确指定知识库。
ALTER TABLE knowledge_import
    ALTER COLUMN knowledge_base_id DROP DEFAULT;

-- 与当前配置一致：1024 维、COSINE_DISTANCE、HNSW。
-- 如向量表已存在，则保留原表。
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS vector_store (
                                            id UUID PRIMARY KEY,
                                            content TEXT,
                                            metadata JSON,
                                            embedding VECTOR(1024)
    );

COMMENT ON TABLE vector_store IS '知识库文档向量存储';
COMMENT ON COLUMN vector_store.id IS '文档片段唯一标识';
COMMENT ON COLUMN vector_store.content IS '文档片段文本内容';
COMMENT ON COLUMN vector_store.metadata IS '文档片段元数据，包含知识库编号、文件哈希等信息';
COMMENT ON COLUMN vector_store.embedding IS '文档片段的向量表示，维度为1024';

CREATE INDEX IF NOT EXISTS idx_vector_store_embedding_hnsw
    ON vector_store USING hnsw (embedding vector_cosine_ops);

-- 给旧向量补充知识库归属；使用字符串，和 Java 写入保持一致。
UPDATE vector_store
SET metadata = (
    COALESCE(metadata::jsonb, '{}'::jsonb)
        || jsonb_build_object('knowledge_base_id', '1')
    )::json
WHERE metadata ->> 'knowledge_base_id' IS NULL;

CREATE INDEX IF NOT EXISTS idx_vector_store_knowledge_base
    ON vector_store ((metadata ->> 'knowledge_base_id'));
